// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SetPieceReducer from "../set_piece_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartRaceReducer from "../start_race_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SetPieceParams = __Infer<typeof SetPieceReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartRaceParams = __Infer<typeof StartRaceReducer>;

