// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import QuickPlayReducer from "../quick_play_reducer";
import SetBotCountReducer from "../set_bot_count_reducer";
import SetReadyReducer from "../set_ready_reducer";
import SetRoomPieceReducer from "../set_room_piece_reducer";
import StartRaceReducer from "../start_race_reducer";
import SubmitMoveReducer from "../submit_move_reducer";
import UseItemReducer from "../use_item_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type QuickPlayParams = __Infer<typeof QuickPlayReducer>;
export type SetBotCountParams = __Infer<typeof SetBotCountReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type SetRoomPieceParams = __Infer<typeof SetRoomPieceReducer>;
export type StartRaceParams = __Infer<typeof StartRaceReducer>;
export type SubmitMoveParams = __Infer<typeof SubmitMoveReducer>;
export type UseItemParams = __Infer<typeof UseItemReducer>;

