// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  roomCode: __t.string().name("room_code"),
  name: __t.string(),
  piece: __t.string(),
  colorIndex: __t.u32().name("color_index"),
  row: __t.u32(),
  col: __t.u32(),
  isBot: __t.bool().name("is_bot"),
  botKind: __t.string().name("bot_kind"),
  online: __t.bool(),
  ready: __t.bool(),
  finished: __t.bool(),
  finishRank: __t.u32().name("finish_rank"),
  finishedAt: __t.timestamp().name("finished_at"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastMoveAt: __t.timestamp().name("last_move_at"),
  stunnedUntil: __t.timestamp().name("stunned_until"),
  heldItem: __t.string().name("held_item"),
  promotedUntil: __t.timestamp().name("promoted_until"),
});
