// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  roomCode: __t.string().name("room_code"),
  name: __t.string(),
  piece: __t.string(),
  row: __t.u32(),
  col: __t.u32(),
  isBot: __t.bool().name("is_bot"),
  online: __t.bool(),
  ready: __t.bool(),
  finished: __t.bool(),
  finishRank: __t.u32().name("finish_rank"),
  joinedAt: __t.timestamp().name("joined_at"),
  lastMoveAt: __t.timestamp().name("last_move_at"),
});
