// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Obstacle = __t.object("Obstacle", {
  id: __t.u64(),
  roomCode: __t.string(),
  row: __t.u32(),
  col: __t.u32(),
  kind: __t.string(),
});
export type Obstacle = __Infer<typeof Obstacle>;

export const Racer = __t.object("Racer", {
  id: __t.u64(),
  identity: __t.identity(),
  roomCode: __t.string(),
  name: __t.string(),
  piece: __t.string(),
  row: __t.u32(),
  col: __t.u32(),
  isBot: __t.bool(),
  online: __t.bool(),
  ready: __t.bool(),
  finished: __t.bool(),
  finishRank: __t.u32(),
  joinedAt: __t.timestamp(),
  lastMoveAt: __t.timestamp(),
  stunnedUntil: __t.timestamp(),
});
export type Racer = __Infer<typeof Racer>;

export const Room = __t.object("Room", {
  code: __t.string(),
  status: __t.string(),
  seed: __t.u32(),
  host: __t.identity(),
  createdAt: __t.timestamp(),
  startedAt: __t.option(__t.timestamp()),
});
export type Room = __Infer<typeof Room>;

